version: '3'
services:
  api:
    build: .
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/app
      - public-data:/app/public
      - tmp-data:/app/tmp
      - log-data:/app/log
      - /app/node_modules
    ports:
      - "3000:3000"
  web:
    build:
      context: containers/nginx
    ports:
      - 80:80
    volumes:
      - public-data:/app/public
      - tmp-data:/app/tmp
    depends_on:
      - api
volumes:
  public-data:
  tmp-data:
  log-data:
