version: '3'
services:
  db:
    platform: linux/x86_64 # M1チップ対応のため追記
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - gem_data:/usr/local/bundle
    ports:
      - "3001:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  postgres_volume:
  gem_data:
    driver: local

# version: '3'
# services:
#   api:
#     build: .
#     command: bundle exec puma -C config/puma.rb -e production
#     volumes:
#       - .:/myapp
#       - public-data:/myapp/public
#       - tmp-data:/myapp/tmp
#       - log-data:/myapp/log
#     ports:
#       - "3001:3000"
#   web:
#     build:
#       context: containers/nginx
#     ports:
#       - 80:80
#     volumes:
#       - public-data:/myapp/public
#       - tmp-data:/myapp/tmp
# volumes:
#   public-data:
#   tmp-data:
#   log-data:
