version: '3'
services:
  api:
    build: .
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/myapp
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    ports:
      - "3001:3000"
  web:
    build:
      context: containers/nginx
    ports:
      - 80:80
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    depends_on:
      - api
volumes:
  public-data:
  tmp-data:
  log-data:
