# fly.toml app configuration file generated for fishare-backend on 2023-06-27T20:53:56+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fishare-backend"
primary_region = "nrt"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/myapp/public"
  url_prefix = "/"
